import Logo from "@/assets/icons/logo.svg"
import User from "@/assets/icons/1.svg"
import Search from "@/assets/icons/2.svg"
import Heart from "@/assets/icons/3.svg"
import Cart from "@/assets/icons/4.svg"
import Ft1 from "@/assets/icons/ft1.svg"
import Ft2 from "@/assets/icons/ft2.svg"
import Ft3 from "@/assets/icons/ft3.svg"
import Compare from "@/assets/icons/cp.svg"
import Stars from "@/assets/icons/stars.svg"
import Delete from "@/assets/icons/delete.svg"
export { Logo, User, Search, Heart, Cart, Ft1, Ft2, Ft3, Compare, Stars, Delete }